import type { Metadata } from "next";
import { Archivo, Overpass } from "next/font/google";
import "./globals.css";

const archivo = Archivo({
  subsets: ["latin"],
});

const overpass = Overpass({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.className} ${overpass.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
